version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongP@ssw0rd
    ports:
      - 1433:1433
    healthcheck:
      test: "exit 0"
    volumes:
      - sqlserver_data:/var/opt/mssql
  redis:
    image: redis:5.0.8-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    healthcheck:
      test: "exit 0"
    volumes:
      - redis_data:/data

volumes:
  sqlserver_data:
  redis_data:
